### ISSUE TITLE
Unable to authenticate to Salesforce sandbox instance

### ISSUE THREAD

**Issue by senithdesilva** [newrelic/newrelic-logs-salesforce-eventlogfile#6]
Hi there, 

I am trying to create a test integration with Salesforce and I have been following the instruction in this repo, but unable to proceed due to the following issue. 

- Response returned from salesforce integration is not a json format response. 

its returning the following response.. 

<!doctype html><html data-adblockkey="MFwwDQYJK=_Tq27JooyshPoUv3e/16JD0Ordl4MQPeQuaY+CyP/HMougJ7TN890yln61ezWvVMFikSkjVu7ZJbSjhT2cHgpjw=="><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="preconnect" href="https://www.google.com" crossorigin></head><body><div id="target" style='opacity: 0'></div><script>window.park = "ey1MDVjZGEtZmMlwvdG9rZW4/Z3JhbnRfdHlwZT1wYXNzd29yZCZjbGllbnRfaDQ3QzIxOTNGN0U5ODI0ODM4NjU5RUZCN0ExIiwidXNlcm5hbWUiOiJhc2ZAc29kYXN0cmF0ZWdpYy5jb20uYXUudWF0IiwicGFzc3dvcmQiOiJDYXRlcnBpbGxhcjA0In0sInBhZ2VfaGVhZGVycyI6W10sImhvc3QiOiJ0ZXN0LnNhc2xlc2ZvcmNlLmNvbSIsImlwIjoiMjExLjMxLjE3Ni4xMjEifQ==";</script><script src="/js/parking.2.105.3.js"></script></body></html>

Error stack
`Traceback (most recent call last):
  File "/Users/sedesilva/dev/repo/newrelic/newrelic-logs-salesforce-eventlogfile/src/__main__.py", line 102, in <module>
    main()
  File "/Users/sedesilva/dev/repo/newrelic/newrelic-logs-salesforce-eventlogfile/src/__main__.py", line 79, in main
    integration.run()
  File "/Users/sedesilva/dev/repo/newrelic/newrelic-logs-salesforce-eventlogfile/src/newrelic_logging/integration.py", line 48, in run
    if not client.authenticate_with_password(sfdc_session):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sedesilva/dev/repo/newrelic/newrelic-logs-salesforce-eventlogfile/src/newrelic_logging/salesforce.py", line 175, in authenticate_with_password
    resp_json = resp.json()
                ^^^^^^^^^^^
  File "/Users/sedesilva/Library/Python/3.11/lib/python/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

im using the password grant type 
<img width="573" alt="image" src="https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/31381386/4b97e4f2-7f95-458b-a7f0-d435f51fe9d5">

Could anyone help? 

FYI, i'm using python3, if that makes any diff.

**Comment by senithdesilva** [comment]
Thanks @shahramk, will go through this and give it a go.

**Comment by asllop** [comment]
@senithdesilva did you fix the issue? Also, we released a new version last week: https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/releases/tag/1.0.0

**Comment by asllop** [comment]
Closing due to inactivity.
