### ISSUE TITLE
Salesforce and new relic connection error

### ISSUE THREAD

**Issue by rajkumarmuthusamy** [newrelic/newrelic-logs-salesforce-eventlogfile#7]
Trying to connect newrelic with salesforce and getting below error only in salesforce production , the same code is used in non-prod/sandboxes are working as expected.

## Relevant Logs / Console output

python src/__main__.py

using program arguments []

Running query SELECT+Id,+EventType,+CreatedDate,+LogDate,+Interval,+LogFile,+Sequence+From+EventLogFile+Where+LogDate>=2023-05-31T13:43:51.957Z+AND+LogDate<2023-05-31T14:43:52.127Z+AND+Interval='Hourly'

Traceback (most recent call last):

 File "/home/ec2-user/newrelic-logs-salesforce-eventlogfile-main/src/__main__.py", line 102, in <module>

  main()

 File "/home/ec2-user/newrelic-logs-salesforce-eventlogfile-main/src/__main__.py", line 79, in main

  integration.run()

 File "/home/ec2-user/newrelic-logs-salesforce-eventlogfile-main/src/newrelic_logging/[integration.py](https://forum.newrelic.com/s/hubtopic/aAX8W0000015BAMWA2/void(0))", line 56, in run

  logs = client.fetch_logs(sfdc_session)

 File "/home/ec2-user/newrelic-logs-salesforce-eventlogfile-main/src/newrelic_logging/[salesforce.py](https://forum.newrelic.com/s/hubtopic/aAX8W0000015BAMWA2/void(0))", line 287, in fetch_logs

  csv_rows = self.parse_csv(download_response, record_id, record_event_type, cached_messages)

 File "/home/ec2-user/newrelic-logs-salesforce-eventlogfile-main/src/newrelic_logging/[salesforce.py](https://forum.newrelic.com/s/hubtopic/aAX8W0000015BAMWA2/void(0))", line 240, in parse_csv

  for row in reader:

 File "/usr/lib64/python3.9/[csv.py](https://forum.newrelic.com/s/hubtopic/aAX8W0000015BAMWA2/void(0))", line 111, in __next__

  row = next(self.reader)

_csv.Error: line contains NUL
## Your Environment

[TIP]:  # Salesforce PROD

**Comment by rajkumarmuthusamy** [comment]
Any guidance on this issue ?

**Comment by asllop** [comment]
Hi @rajkumarmuthusamy ! Is this still happening? I've been trying to reproduce but I couldn't. To me, looks like a corrupt CSV file that contains null bytes.

**Comment by asllop** [comment]
Closing due to inactivity.
